CREATE TABLE CAMPAIGNS(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME TEXT NOT NULL,
    KEY_WORDS TEXT ARRAY NOT NULL,
    BID DECFLOAT NOT NULL,
    FUND DECFLOAT NOT NULL,
    STATUS ENUM('ON', 'OFF') NOT NULL,
    TOWN TEXT,
    RADIUS DECIMAL NOT NULL
);